version: '3'
services:
    nginx:
        container_name: "compose-nginx"
        image: nginx:latest
        restart: always
        ports:
            - "80:80"
#            - "443:443"
        environment:
            - TZ=Asia/Shanghai
        depends_on:
            - "php"
        volumes:
            - "../nginx/conf.d:/etc/nginx/conf.d"
            - "../nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
            - "/Users/tony/code:/usr/share/nginx/html"
            - "../nginx/log:/var/log/nginx/"
        networks:
            app_net:
                ipv4_address: 10.10.10.2
    php:
        build: ./php-extension
        image: php:7.4
        restart: always
        ports:
            - "9000:9000"
        volumes:
            - "/Users/tony/code:/var/www/html"
            - "../php74/etc:/usr/local/etc"
            - "../php74/log:/var/log/php"
        stdin_open: true
        tty: true
        links:
            - "mysql"
        networks:
            app_net:
                ipv4_address: 10.10.10.3
        environment:
            WEBROOT: '/var/www/html/public'
            TZ: 'Asia/Shanghai'
        container_name: "compose-php"
    mysql:
        platform: linux/x86_64
        image: mysql:5.7
        ports:
            - "33060:3306"
        volumes:
            - "../mysql/data:/var/lib/mysql"
            - "../mysql/conf:/etc/mysql/conf.d"
            - "../mysql/logs:/data/mysql/logs"
        restart: always
        environment:
            - TZ=Asia/Shanghai
            - MYSQL_USER=homestead
            - MYSQL_PASSWORD=secret
            - MYSQL_ROOT_PASSWORD=root123
            - MYSQL_ROOT_HOST="%"
        networks:
            app_net:
                ipv4_address: 10.10.10.1     
        container_name: "compose-mysql"
    redis:
        image: redis:5
        restart: always
        ports:
            - 6379:6379
        volumes:
            - "../redis/conf:/usr/local/etc/redis"
            - "../redis/data:/data"
        command:
          redis-server /usr/local/etc/redis/redis.conf --requirepass root123
        environment:
            - TZ=Asia/Shanghai
        container_name: "compose-redis"
networks:
    app_net:
        driver: bridge
        driver_opts:
          com.docker.network.enable_ipv6: "true"
        ipam:
            config:
                - subnet: 10.10.0.0/16
